// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvcJ7aitmjmy8MAZySFyyDLV6l-HOtEwg',
    appId: '1:526358949411:web:c246f02192c69ae3250b96',
    messagingSenderId: '526358949411',
    projectId: 'shopline-app-admin',
    authDomain: 'shopline-app-admin.firebaseapp.com',
    storageBucket: 'shopline-app-admin.firebasestorage.app',
    measurementId: 'G-FR3774FXR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQieH_b0aTpkWwFyVnxWKI2sVMFc-mVD8',
    appId: '1:526358949411:android:aeeca1fe96afbbf8250b96',
    messagingSenderId: '526358949411',
    projectId: 'shopline-app-admin',
    storageBucket: 'shopline-app-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFL8VgVKEc6l_rE5eqvTRVsEx5rNsve4',
    appId: '1:526358949411:ios:285cc40f8ea99746250b96',
    messagingSenderId: '526358949411',
    projectId: 'shopline-app-admin',
    storageBucket: 'shopline-app-admin.firebasestorage.app',
    iosBundleId: 'com.panamex.shoplinerepartidor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFL8VgVKEc6l_rE5eqvTRVsEx5rNsve4',
    appId: '1:526358949411:ios:e880f527e0e8fa9a250b96',
    messagingSenderId: '526358949411',
    projectId: 'shopline-app-admin',
    storageBucket: 'shopline-app-admin.firebasestorage.app',
    iosBundleId: 'com.panamex.shoplinerepartidorflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvcJ7aitmjmy8MAZySFyyDLV6l-HOtEwg',
    appId: '1:526358949411:web:09c4854431a1a276250b96',
    messagingSenderId: '526358949411',
    projectId: 'shopline-app-admin',
    authDomain: 'shopline-app-admin.firebaseapp.com',
    storageBucket: 'shopline-app-admin.firebasestorage.app',
    measurementId: 'G-VZJFD5LK9G',
  );
}
