// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoBXtlHk0dC5O9F9rgyfxRXKY5_VRgrk',
    appId: '1:1055843416603:web:15d76a3b6f9048b72256be',
    messagingSenderId: '1055843416603',
    projectId: 'shopline-app-8c49f',
    authDomain: 'shopline-app-8c49f.firebaseapp.com',
    storageBucket: 'shopline-app-8c49f.appspot.com',
    measurementId: 'G-YYJVQSHYLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSi8JQGupIBlx1w279zG0xPZEtLmlnyg',
    appId: '1:1055843416603:android:7ffd1a642c47013b2256be',
    messagingSenderId: '1055843416603',
    projectId: 'shopline-app-8c49f',
    storageBucket: 'shopline-app-8c49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdd9tJ8OmEICwGFRGBuJuK1CLPX7XPEjM',
    appId: '1:1055843416603:ios:6a2949cdedadf7332256be',
    messagingSenderId: '1055843416603',
    projectId: 'shopline-app-8c49f',
    storageBucket: 'shopline-app-8c49f.appspot.com',
    iosBundleId: 'com.panamex.shopline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdd9tJ8OmEICwGFRGBuJuK1CLPX7XPEjM',
    appId: '1:1055843416603:ios:36058d189b9b3c5d2256be',
    messagingSenderId: '1055843416603',
    projectId: 'shopline-app-8c49f',
    storageBucket: 'shopline-app-8c49f.appspot.com',
    iosBundleId: 'com.panamex.shoplineflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfoBXtlHk0dC5O9F9rgyfxRXKY5_VRgrk',
    appId: '1:1055843416603:web:31174b665f38a4382256be',
    messagingSenderId: '1055843416603',
    projectId: 'shopline-app-8c49f',
    authDomain: 'shopline-app-8c49f.firebaseapp.com',
    storageBucket: 'shopline-app-8c49f.appspot.com',
    measurementId: 'G-R6WQLEXKVF',
  );
}
